const data = {
    products: [
        {
            _id: '1',
            name: 'Classic 50\'s dress',
            category: 'Woman Dress',
            image: '/images/product-1.jpg',
            price: 240,
            countInStock: 3,
            brand: 'Hugo Boss',
            rating: 3.5,
            numReviews: 10,
            description: 'high quality product', 
        },
        {
            _id: '2',
            name: 'Classic woman from the 50\'s - 1',
            category: 'Classic Photos',
            image: '/images/product-2.jpg',
            price: 50,
            countInStock: 10,
            brand: 'none',
            rating: 4.0,
            numReviews: 10,
            description: 'high quality product', 
        },
        {
            _id: '3',
            name: 'Classic woman from the 50\'s - 2',
            category: 'Photo',
            image: '/images/product-3.jpg',
            price: 60,
            countInStock: 4,
            brand: 'None',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product', 
        },
        {
            _id: '4',
            name: 'Posing woman from the 50\'s ',
            category: 'Classic Photos',
            image: '/images/product-4.jpg',
            price: 70,
            countInStock: 8,
            brand: 'none',
            rating: 4.0,
            numReviews: 10,
            description: 'high quality product', 
        },
        {
            _id: '5',
            name: 'Classic Micro Phone',
            category: 'Microphone',
            image: '/images/product-5.jpg',
            price: 999,
            countInStock: 2,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product', 
        },
        {
            _id: '6',
            name: 'Woman in kitchen',
            category: 'Photos',
            image: '/images/product-6.jpg',
            price: 60,
            countInStock: 8,
            brand: 'None',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product', 
        },
    ],
};

export default data;